# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddMovie.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
'''
Store = {"movie" : {
                "duration" : 0,
                "casts" : { 
                    "riddhi" : {
                        "gender" : "male",
                        "NAME" : "",
                        "character" :"" 
                        "dialog" : {
                            'fuck yoou' : { "from" : 0 , "to" : 0}
                            ''
                        }
                    }
                }
        }
}
'''
from PyQt5 import QtCore, QtGui, QtWidgets
from AddCast import Ui_AddCastWindow
import storage as database



storage = {}

class Ui_enterMovieWindow(object):
    def setupUi(self, enterMovieWindow, storage):
        enterMovieWindow.setObjectName("enterMovieWindow")
        enterMovieWindow.resize(441, 223)
        self.centralwidget = QtWidgets.QWidget(enterMovieWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.movieName = QtWidgets.QLabel(self.centralwidget)
        self.movieName.setGeometry(QtCore.QRect(30, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.movieName.setFont(font)
        self.movieName.setObjectName("movieName")
        self.movieNameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.movieNameInput.setGeometry(QtCore.QRect(30, 30, 221, 21))
        self.movieNameInput.setObjectName("movieNameInput")
        movie_name = self.movieNameInput.text()
        storage[movie_name] = {}
        self.AddCast = QtWidgets.QPushButton(self.centralwidget , clicked = lambda:self.onClickAddCast())
        self.AddCast.setGeometry(QtCore.QRect(30, 70, 391, 51))
        self.AddCast.setObjectName("AddCast")

        self.SaveData = QtWidgets.QPushButton(self.centralwidget , clicked = lambda:self.saveExit(storage) )
        self.SaveData.setGeometry(QtCore.QRect(30, 140, 101, 31))
        self.SaveData.setObjectName("SaveData")
        self.MovieDurationLabel = QtWidgets.QLabel(self.centralwidget)
        self.MovieDurationLabel.setGeometry(QtCore.QRect(300, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MovieDurationLabel.setFont(font)
        self.MovieDurationLabel.setObjectName("MovieDurationLabel")
        self.MovieDurationInput = QtWidgets.QTimeEdit(self.centralwidget)
        self.MovieDurationInput.setGeometry(QtCore.QRect(300, 30, 118, 22))
        self.MovieDurationInput.setObjectName("MovieDurationInput")
        duration = self.MovieDurationInput.specialValueText()
        storage[movie_name]["duration"] = duration
        storage[movie_name]["casts"] = {}
        enterMovieWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(enterMovieWindow)
        self.statusbar.setObjectName("statusbar")
        enterMovieWindow.setStatusBar(self.statusbar)

        self.retranslateUi(enterMovieWindow)
        QtCore.QMetaObject.connectSlotsByName(enterMovieWindow)

        

    def retranslateUi(self, enterMovieWindow):
        _translate = QtCore.QCoreApplication.translate
        enterMovieWindow.setWindowTitle(_translate("enterMovieWindow", "MainWindow"))
        self.movieName.setText(_translate("enterMovieWindow", "Enter Movie Name"))
        self.AddCast.setText(_translate("enterMovieWindow", "Add Cast"))
        self.SaveData.setText(_translate("enterMovieWindow", "Save and Exit"))
        self.MovieDurationLabel.setText(_translate("enterMovieWindow", "Movie Duration"))
        self.MovieDurationInput.setDisplayFormat(_translate("enterMovieWindow", "HH:mm:ss"))

    def onClickAddCast(self):
        self.window = QtWidgets.QMainWindow()
        self.addCastUi = Ui_AddCastWindow()
        self.addCastUi.setupUi(self.window)
        self.window.show()
    
    def saveExit(self, storage):
        database.dump(storage, self.sdf)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    enterMovieWindow = QtWidgets.QMainWindow()
    ui = Ui_enterMovieWindow()
    ui.setupUi(enterMovieWindow, storage=storage)
    enterMovieWindow.show()
    sys.exit(app.exec_())
